import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from "react";
import Header from "@/components/UI/Header/Header";
import { dashboardActions } from "@/store/dashboardReducer";

const inter = Inter({ subsets: ["latin"] });

const Main = () => {
  const dispatch = useDispatch();
  
  useEffect(() => {
    dispatch(dashboardActions.setTheme());
  },[]);

  return (
    <>
      <Head>
        <title>Ashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className} ${styles.body_gradiant}`}>
        
        <h1>
          Welcome
        </h1>
        {/* <Link href='/career/projects'>Go to Projects</Link> */}
        
        
      </main>
    </>
    );
}

export default Main;